name: Run Selenium Test

on:
  push:
    branches: ["master"]
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          cache: maven
          distribution: "temurin"
      - uses: browser-actions/setup-chrome@latest
      - name: Setup Fluxbox and Xvfb
        run: |
          sudo apt-get -y install fluxbox libxss1 libappindicator3-1 libindicator7

          Xvfb :99 &
          fluxbox -display :99 &
          echo "DISPLAY=:99" >> "$GITHUB_ENV"
      - run: mvn clean test
      

      - name: Generate Allure Report
        run: mvn allure:report
      
      - name: Deploy to Github Pages.
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/allure-results

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

